### ISSUE TITLE
Consider migrating multithreading utils to java.lang.Thread

### ISSUE THREAD

**Issue by paul-griffith** [design-group/ignition-gateway-utilities#10]
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html

Java threads can have a `DefaultExceptionHandler`:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#setDefaultUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler)

Java threads can be assigned a subsystem (shows up on the diagnostics page):
https://files.inductiveautomation.com/sdk/javadoc/ignition81/8.1.21/com/inductiveautomation/ignition/common/execution/TPC.html

Java threads can be assigned a description (shows up in 'running threads' diagnostics):
https://files.inductiveautomation.com/sdk/javadoc/ignition81/8.1.21/com/inductiveautomation/ignition/common/script/ScriptContext.html

You might also consider using an `Executor`:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/Executors.html
Which you could pair with a named ThreadFactory:
https://files.inductiveautomation.com/sdk/javadoc/ignition81/8.1.21/com/inductiveautomation/ignition/common/execution/TPC.html#newThreadFactory(java.lang.String,java.lang.String)

**Comment by keith-gamble** [comment]
Migrated to `java.lang.Thread` in #11, good call!
